import type { Metadata } from "next";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import "./globals.css";
import Service from "../../components/Home/Service";
import { SessionContextWrapper } from "@/app/sessionContext";
import Providers from "./provider";
export const metadata: Metadata = {
  title: "E-commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-black overflow-x-hidden">
        <Navbar />
        <div>
          <Providers>
            <SessionContextWrapper>{children}</SessionContextWrapper>
          </Providers>
        </div>
        <div className="grid grid-cols-2 lg:flex flex-row items-center justify-center  gap-2 py-3 px-2">
          <Service />
          <Service />
          <Service />
          <Service />
        </div>
        <Footer />
      </body>
    </html>
  );
}
